VERSION: 2
#model: deit_tiny_patch16_224
model_cfg:
  type: VisionTransformer
  kwargs:
    patch_size: 16
    embed_dim: 384
    depth: 12
    num_heads: 6
    pretrained: false
    num_classes: 1000
    drop_rate: 0.
    drop_path_rate: 0.1
batch_size: 128
aa: ''
mixup: 0.
cutmix: 0.
repeated_aug: false
reprob: 0.
